"""
Stage B4: Local royalty-free music selection and mixing helpers.
Now with synthetic fallback, mood-aware selection, and crossfade looping.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional, List

import subprocess
try:
    from pydub import AudioSegment
except Exception:
    AudioSegment = None

try:
    from ..config import settings
except ImportError:
    from config import settings


# Mood keywords for track scoring
MOOD_KEYWORDS = {
    "upbeat": ["upbeat", "energetic", "happy", "bright", "cheerful", "fun", "lively"],
    "calm": ["calm", "ambient", "peaceful", "relaxing", "serene", "gentle", "soft"],
    "dramatic": ["dramatic", "cinematic", "epic", "intense", "powerful", "bold"],
    "corporate": ["corporate", "business", "professional", "modern", "clean"],
    "emotional": ["emotional", "sentimental", "warm", "heartfelt", "touching"],
    "electronic": ["electronic", "tech", "digital", "synth", "futuristic"],
    "acoustic": ["acoustic", "organic", "natural", "warm", "folk", "guitar"],
}


def _score_track_for_mood(track_path: Path, mood: str) -> int:
    """Score a track filename against the desired mood using keyword matching."""
    name_lower = track_path.stem.lower()
    mood_lower = mood.lower().strip()
    score = 0

    # Exact mood match in filename
    if mood_lower in name_lower:
        score += 10

    # Keyword matching from mood synonym table
    for mood_group, keywords in MOOD_KEYWORDS.items():
        if mood_lower in keywords or mood_lower == mood_group:
            for kw in keywords:
                if kw in name_lower:
                    score += 3
                    break

    # Partial match
    for word in mood_lower.split():
        if word in name_lower:
            score += 2

    return score


def _find_music_file(mood: str) -> Optional[Path]:
    music_dir = Path(settings.local_music_dir)
    if not music_dir.exists():
        music_dir.mkdir(parents=True, exist_ok=True)

    candidates = sorted(music_dir.glob("*.mp3")) + sorted(music_dir.glob("*.wav"))
    if not candidates:
        # H6 FIX: Do NOT download from external CDN at runtime.
        # Use synthetic fallback (generated by _generate_synthetic_ambient) instead.
        return None

    # Score all candidates by mood relevance
    scored = [(track, _score_track_for_mood(track, mood)) for track in candidates]
    scored.sort(key=lambda x: x[1], reverse=True)

    # Return highest scored track (falls back to first track if no mood match)
    return scored[0][0]


def _generate_synthetic_ambient(output_path: str, duration: int = 30) -> str:
    """Generate a synthetic ambient music track using FFmpeg audio synthesis.
    
    Creates a low, pulsing ambient tone — not silence, not great, but usable.
    """
    cmd = [
        "ffmpeg", "-y",
        "-f", "lavfi",
        "-i", f"sine=frequency=220:duration={duration}",
        "-af", "tremolo=f=5:d=0.4,volume=0.3",
        str(output_path)
    ]
    result = subprocess.run(cmd, capture_output=True, timeout=30)
    if result.returncode != 0:
        raise RuntimeError(f"Synthetic music generation failed: {result.stderr.decode()[:200]}")
    return str(output_path)


def generate_background_music(duration_seconds: int, output_dir: str, mood: str = "upbeat", job_id: str = "unknown") -> str:
    """
    Pick a local royalty-free track and trim/loop it to requested duration.
    Falls back to synthetic ambient when no track is available.
    """
    try:
        from ..pipeline.progress import pub_log
    except ImportError:
        from pipeline.progress import pub_log

    pub_log(job_id, "music", f"MUSIC Generating background track (mood={mood})", pct=10)

    output_path = Path(output_dir) / "music.mp3"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    target_seconds = max(1, duration_seconds)
    source_track = _find_music_file(mood)

    if source_track is None:
        # Synthetic fallback instead of raising
        pub_log(job_id, "music", "MUSIC ⚠ No tracks found, generating synthetic ambient track", pct=30)
        try:
            result = _generate_synthetic_ambient(str(output_path), target_seconds)
            pub_log(job_id, "music", "MUSIC ✓ Synthetic ambient track generated", pct=100)
            return result
        except Exception as e:
            pub_log(job_id, "music", f"MUSIC ✗ Synthetic generation failed: {e}", pct=50)
            raise Exception(f"Music Failed: No tracks found and synthetic generation failed: {e}")

    pub_log(job_id, "music", f"MUSIC Selected track: {source_track.name} (mood={mood})", pct=40)

    # Loop with crossfade to avoid audible seams
    fade_start = max(0, target_seconds - 5)
    cmd = [
        "ffmpeg", "-y",
        "-stream_loop", "-1",  # Loop indefinitely in case track is short
        "-i", str(source_track),
        "-t", str(target_seconds),
        "-af", f"afade=t=in:d=1,afade=t=out:st={fade_start}:d=5",
        str(output_path)
    ]
    result = subprocess.run(cmd, capture_output=True, timeout=15)

    if result.returncode != 0:
        # Try without crossfade
        pub_log(job_id, "music", "MUSIC ⚠ Crossfade failed, trying simple loop", pct=60)
        cmd_simple = [
            "ffmpeg", "-y",
            "-stream_loop", "-1",
            "-i", str(source_track),
            "-t", str(target_seconds),
            "-af", f"afade=t=out:st={fade_start}:d=5",
            str(output_path)
        ]
        subprocess.run(cmd_simple, capture_output=True, timeout=15)
    
    pub_log(job_id, "music", "MUSIC ✓ music.mp3 generated", pct=100)
    return str(output_path)


def mix_voice_with_music(voice_path: str, music_path: str, output_path: str, music_gain_db: int = -18) -> str:
    """Overlay low-volume background music under generated narration."""

    if AudioSegment is None:
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        subprocess.run([
            "ffmpeg", "-y",
            "-i", voice_path,
            "-i", music_path,
            "-filter_complex", f"[1:a]volume={music_gain_db}dB[music];[0:a][music]amix=inputs=2:duration=first[a]",
            "-map", "[a]",
            output_path
        ], capture_output=True, timeout=settings.ollama_request_timeout)
        return output_path

    voice = AudioSegment.from_file(voice_path)
    music = AudioSegment.from_file(music_path) + music_gain_db

    if len(music) < len(voice):
        loops = (len(voice) // len(music)) + 1
        music = music * loops

    mixed = voice.overlay(music[: len(voice)])
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    mixed.export(output_path, format="wav")
    return output_path